### ISSUE TITLE
use with phonegap or standalone?

### ISSUE THREAD

**Issue by agreif** [bencompton/framework7-react-app-template#2]
Hi,
I am quite new to mobile app development and have the following question:
should a f7-react project developed and distrubuted alone or as part of a phonegap project?
The background of my question is that I first looked at phonegap and saw that it can be nicely used with f7. But then in this README.md I see that this f7-react project can be deployed too. So I am a bit confused which way to go.
thanks.

**Comment by bencompton** [comment]
When you develop a web app with Framework7 React, you end up with HTML, CSS, and JavaScript (for example, if you use the starter template and run `npm run build`, you will get HTML, CSS, and JavaScript in the build folder). You can take that and deploy it on a web server, and people can use your app in a web browser. Users can also add your app to the home screen from iOS Safari or Android Chrome and your app will have a launch icon on the home screen, run full screen, and work a lot like a native app from there (assuming you have the correct meta tags in your index.html).

The other alternative is to make a hybrid app and take the HTML, CSS, and JavaScript and use it in a PhoneGap / Cordova project. This basically runs your HTML, CSS, and JavaScript inside of a web browser within a native app, and also allows you to get access to native APIs that you can't access from a pure web app. This also means that your app will be distributed from the Apple App Store or Google Play Store instead of from your website. Making a starter template for Cordova is still on the todo list for Framework7 React.

Ultimately, the approach you take depends on the needs of your project. For instance, do you want to distribute your app from app stores or from a website, or do you need access to native APIs (like the camera)? If so, then you should use PhoneGap or Cordova. If you want to distribute your app as a pure web app and perhaps have users add it to the home screen from your website, then you don't need PhoneGap or Cordova.

Hope that helps.

**Comment by agreif** [comment]
Hi Ben,
many thanks for the thorough explanation, and yes it helps a lot for my understanding.
Indeed I will need camera access out of the app, so I will need the PhoneGap/Cordova approach. Independently from which way I choose, I want to use React, because it suites my thinking the most. So I am very curious when your starter template will be released and then definitely give it a try. Until then I will get used to the PhoneGap/Cordova/f7 bundle.
thanks.
