### ISSUE TITLE
themeType="ios" hardcoded in App.jsx

### ISSUE THREAD

**Issue by agreif** [bencompton/framework7-react-app-template#3]
I just found that in App.jsx the themeType is hardcoded like this

    themeType="ios"

Is this intentional?
I tried to change it to "material" but I could not see any changes ... or maybe I reloaded the wrong way :)

thanks.

**Comment by bencompton** [comment]
In addition to changing that to `themeType="material", it is also necessary to use the Material CSS.

If you import the Material CSS here instead of the iOS CSS, that should do the trick:

```javascript
//src/index.js

import 'framework7/dist/css/framework7.ios.min.css';
import 'framework7/dist/css/framework7.ios.colors.min.css';

/* OR for Material Theme:
import 'framework7/dist/css/framework7.material.min.css'
import 'framework7/dist/css/framework7.material.colors.min.css'
*/
```

FYI, the Material support is not 100% seamless at this point, meaning that you will have to make changes here and there to make things look right in Material. For example, you'll notice that the navbar doesn't look right in Material. I have been meaning to create an issue in the [Framework7 Vue](https://github.com/nolimits4web/Framework7-Vue/) repo to ask about this (Framework7 React uses Framework7 Vue's rendering logic), so I'll go ahead and do that.

### Edit

https://github.com/nolimits4web/Framework7-Vue/issues/98

**Comment by agreif** [comment]
ok, thanks!
