### ISSUE TITLE
url is not changing on navigating between the pages

### ISSUE THREAD

**Issue by anuragnagarkota** [bencompton/framework7-react-app-template#4]
Hello Ben

First of all thanks a lot for this fantastic integration of F7 with React. I was just wondering why the url is not changing when I click on the Form or About link. Although the page is being opened with fantastic animation but the url is not being changed. Do you have any plans for this in near future.

**Comment by bencompton** [comment]
Hello there! It is sort of supported at the moment, but does have some known issues. If you enable the pushState option on the Framework7App component, the URL will change as you navigate. Depending on your use case, the known issues may or may not affect you. See the "Push State" props section here http://framework7.io/docs/init-app.html for all of the options for configuring push state, and see here if you're not familiar with the Framework7App app component: http://framework7.io/react/init-app.html.

If you look through the [issues in Framework7 Vue](https://github.com/nolimits4web/Framework7-Vue/issues), you'll see the open issues about the router / pushState I am referring to. Since Framework7 React is built on top of Framework7 Vue, these same issues also exist in F7 React. Getting the History API working correctly is a pretty high priority for both versions of the framework. I intend to get around to looking into these soon, but can't exactly promise any time-frames.

**Comment by anuragnagarkota** [comment]
Hey Ben

Thanks a lot. It worked in the way that I wanted exactly. Kudos to you to make our favourite UI(f-7) framework work with our favourite view library(React). 

I encountered the following error when I click on back button of navbar-
framework7-vue.js:2958 Uncaught TypeError: this.$delete is not a function
    at vueComponentClass.onPageBeforeRemove (framework7-vue.js:2958)
    at HTMLDivElement.<anonymous> (PropsProcessor.js:139)
    at Dom7.trigger (Framework7.js:9878)
    at window.Framework7.module.exports.Framework7.app.pageRemoveCallback (Framework7.js:1329)
    at Object.app.router.afterBack (Framework7.js:2687)
    at afterAnimation (Framework7.js:2260)
    at Framework7.js:2293
    at HTMLDivElement.fireCallBack (Framework7.js:9905)

Please let me know can this be removed?

**Comment by bencompton** [comment]
Turns out this template wasn't using the latest version. If you update framework7-react in your package.json to version `0.8.5-beta.6`, the issue will be fixed.

**Comment by anuragnagarkota** [comment]
Thanks Ben! It worked.
